logging:
  level:
    root: info
    com.rest.api: debug

spring:
  profiles: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/nanugi
    driver-class-name: org.h2.Driver
    username: sa

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate:
      hbm2ddl.auto: create
      format_sql: true
    showSql: true
    generate-ddl: true
  url:
    base: http://localhost:8080

mailgun:
  url:
    base: http://localhost:8080